services:
  postgres:
    image: postgres:16-alpine
    container_name: am_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assignment_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: am_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: am_rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI (guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: am_api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=assignment_management;Username=postgres;Password=postgres"
      Jwt__Secret: "docker_dev_super_secret_key_change_me_at_least_32_chars"
      Jwt__Issuer: "AssignmentManagement"
      Jwt__Audience: "AssignmentManagement.Client"
      Jwt__ExpiryMinutes: "120"
      Redis__ConnectionString: "redis:6379"
      Cache__Enabled: "true"
      Cache__ExpirySeconds: "60"
      RabbitMq__Enabled: "true"
      RabbitMq__Host: "rabbitmq"
      RabbitMq__Port: "5672"
      RabbitMq__Username: "guest"
      RabbitMq__Password: "guest"
      Enrollment__UseAsyncProcessing: "true"
      Storage__RootPath: "/app/storage"
    ports:
      - "8080:8080"
    volumes:
      - submissions:/app/storage

volumes:
  pgdata:
  submissions:
